# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9e8d269888820590c737d33e1abf0bc394234b10777428d305f79d77e558cde385554acafa272f89a7e3acf5aebda8a396d49b33b6f3f5fa7438fdbd8505437

test:
  secret_key_base: c00729a6a458e9b1a0102c7ec29586287a6e0d244cf500f144d14c76efe8aaf61d430bd94a457e924238167f9d4518a415e5975f3944592a6ae7b0b45a045ddf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
